name: Oba
description: Oba Boba
version: 1.2.3+1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  image_picker: ^0.6.2+3
  firebase_storage: ^3.1.1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  uuid: ^2.0.4
  image: ^2.1.11
  font_awesome_flutter: ^8.5.0
  async: ^2.4.0
  http: ^0.12.0+3
  shared_preferences: ^0.5.6
  cached_network_image: ^2.0.0
  firebase_messaging: ^6.0.9
  location: ^2.3.5
  geocoder: ^0.2.1
  flare_flutter: ^1.8.3
  provider:
  cupertino_icons: ^0.1.3
  enhanced_future_builder:

#dev_dependencies:
#    flutter_test:
#      sdk: flutter
#    build_runner: ^1.0.0
#    json_serializable: ^2.0.0
#    google_sign_in: ^4.0.7

flutter:
  uses-material-design: true
  fonts:
  - family: Billabong
    fonts:
    - asset: assets/fonts/Billabong.ttf
  assets:
  - assets/
  - assets/logos/
  - assets/images/
  - assets/flare/

